#!/bin/sh
. `dirname $0`/helper.sh

export PROC_STAT=`mktmp "proc_stat"`

echo "cpu  2255 34 2290 22625563 6290 127 456 0 0" > $PROC_STAT

command='meters/cpu-linux'

expected=$(cat <<EOF
user 2255
nice 34
sys 2290
idle 22625563
wait 6290
irq 127
softirq 456
steal 0
EOF)

assert_eq "`$command`" "$expected"

