#!/bin/sh
. `dirname $0`/helper.sh

source_stubs "freebsd"

command='plugins/cpu-freebsd'

expected=$(cat <<EOF
user 737
nice 0
sys 4341
irq 5990
idle 12275482
EOF)

assert_eq "`$command`" "$expected"
