#!/bin/sh

PATH="test/fake/bin:$PATH"
command='plugins/load'
expected=$(cat <<EOF
one 0.99
five 0.99
fifteen 0.94
EOF)
actual=`$command`

if ! [ "${actual}" = "${expected}" ]; then
  echo "${command} failed! Got \"${actual}\", but expected \"${expected}\""
  exit -1
fi
