#!/bin/sh
. `dirname $0`/helper.sh

source_stubs "sunos"

command='plugins/proc'

expected=$(cat <<EOF
load 1.23
total 6
dead 0
idle 0
lock 0
runnable 1
running 1
sleeping 1
stopped 1
uninterruptible 0
waiting 1
zombie 1
EOF)

assert_eq "`$command`" "$expected"
