#!/bin/sh

PATH="test/fake/linux-bin:$PATH"
command='plugins/proc'
expected=$(cat <<EOF
load 3.21
total 7
dead 1
idle 0
lock 0
runnable 1
running 0
sleeping 1
stopped 1
uninterruptible 1
waiting 1
zombie 1
EOF)
actual=`$command`

if ! [ "${actual}" = "${expected}" ]; then
  echo "${command} failed! Got \"${actual}\", but expected \"${expected}\""
  exit -1
fi
