#!/bin/sh

PATH="test/fake/bin:$PATH"
command='plugins/proc'
expected=$(cat <<EOF
load 0.99
total 27
dead 1
idle 2
lock 1
runnable 4
running 1
sleeping 4
stopped 4
uninterruptible 3
waiting 3
zombie 4
EOF)
actual=`$command`

if ! [ "${actual}" = "${expected}" ]; then
  echo "${command} failed! Got \"${actual}\", but expected \"${expected}\""
  exit -1
fi
