#!/bin/sh

. `dirname $0`/helper.sh

PATH="test/fake/bin:$PATH"
command='plugins/redis'

expected=$(cat <<EOF
redis_git_dirty 0
arch_bits 64
process_id 7480
tcp_port 6379
uptime_in_seconds 351866
uptime_in_days 4
hz 10
lru_clock 11304489
connected_clients 1
client_longest_output_list 0
client_biggest_input_buf 0
blocked_clients 0
used_memory 502664
used_memory_rss 1699840
used_memory_peak 503648
used_memory_lua 33792
mem_fragmentation_ratio 3.38
loading 0
rdb_changes_since_last_save 0
rdb_bgsave_in_progress 0
rdb_last_save_time 1420238767
rdb_last_bgsave_time_sec -1
rdb_current_bgsave_time_sec -1
aof_enabled 0
aof_rewrite_in_progress 0
aof_rewrite_scheduled 0
aof_last_rewrite_time_sec -1
aof_current_rewrite_time_sec -1
total_connections_received 85
total_commands_processed 84
instantaneous_ops_per_sec 0
rejected_connections 0
sync_full 0
sync_partial_ok 0
sync_partial_err 0
expired_keys 0
evicted_keys 0
keyspace_hits 0
keyspace_misses 0
pubsub_channels 0
pubsub_patterns 0
latest_fork_usec 0
connected_slaves 0
master_repl_offset 0
repl_backlog_active 0
repl_backlog_size 1048576
repl_backlog_first_byte_offset 0
repl_backlog_histlen 0
used_cpu_sys 90.95
used_cpu_user 47.83
used_cpu_sys_children 0.00
used_cpu_user_children 0.00
EOF)

assert_eq "`$command`" "$expected"
