#!/bin/sh
# ps - stub `ps -Ao state=` output from linux

echo D # uninterruptible sleep (usually IO)
echo R # running or runnable (on run queue)
echo S # interruptible sleep (waiting for an event to complete)
echo T # stopped, either by a job control signal or because it is being traced
echo W # paging (not valid since the 2.6.xx kernel)
echo X # dead (should never be seen)
echo Z # defunct ("zombie") process, terminated but not reaped by its parent
